// src/lib/mock-data.ts
// Data dummy untuk development

export const mockMassSchedules = [
  {
    id: 1,
    dayOfWeek: "Senin",
    time: "06:00",
    location: "Gereja Paroki",
    celebrant: "Rm. Andreas Wahyu, Pr",
    notes: "Misa Harian",
    isActive: true,
  },
  {
    id: 2,
    dayOfWeek: "Selasa",
    time: "06:00",
    location: "Gereja Paroki",
    celebrant: "Rm. Benediktus Surya, Pr",
    notes: "Misa Harian",
    isActive: true,
  },
  {
    id: 3,
    dayOfWeek: "Rabu",
    time: "06:00",
    location: "Gereja Paroki",
    celebrant: "Rm. Andreas Wahyu, Pr",
    notes: "Misa Harian",
    isActive: true,
  },
  {
    id: 4,
    dayOfWeek: "Kamis",
    time: "06:00",
    location: "Gereja Paroki",
    celebrant: "Rm. Benediktus Surya, Pr",
    notes: "Misa Harian",
    isActive: true,
  },
  {
    id: 5,
    dayOfWeek: "Jumat",
    time: "06:00",
    location: "Gereja Paroki",
    celebrant: "Rm. Andreas Wahyu, Pr",
    notes: "Misa Harian",
    isActive: true,
  },
  {
    id: 6,
    dayOfWeek: "Sabtu",
    time: "06:00",
    location: "Gereja Paroki",
    celebrant: "Rm. Benediktus Surya, Pr",
    notes: "Misa Harian",
    isActive: true,
  },
  {
    id: 7,
    dayOfWeek: "Sabtu",
    time: "17:00",
    location: "Gereja Paroki",
    celebrant: "Rm. Andreas Wahyu, Pr",
    notes: "Misa Sabtu Sore (Vigili Minggu)",
    isActive: true,
  },
  {
    id: 8,
    dayOfWeek: "Minggu",
    time: "07:00",
    location: "Gereja Paroki",
    celebrant: "Rm. Benediktus Surya, Pr",
    notes: "Misa Minggu Pertama",
    isActive: true,
  },
  {
    id: 9,
    dayOfWeek: "Minggu",
    time: "09:00",
    location: "Gereja Paroki",
    celebrant: "Rm. Andreas Wahyu, Pr",
    notes: "Misa Minggu Bahasa Indonesia",
    isActive: true,
  },
  {
    id: 10,
    dayOfWeek: "Minggu",
    time: "17:00",
    location: "Gereja Paroki",
    celebrant: "Rm. Benediktus Surya, Pr",
    notes: "Misa Minggu Sore",
    isActive: true,
  },
];

export const mockPosts = [
  {
    id: 1,
    title: "Perayaan Pesta Nama Paroki Keluarga Kudus 2024",
    slug: "perayaan-pesta-nama-paroki-keluarga-kudus-2024",
    excerpt: "Paroki Keluarga Kudus Atmodirono merayakan pesta nama paroki dengan berbagai kegiatan rohani dan sosial yang meriah bersama seluruh umat.",
    content: "<p>Paroki Keluarga Kudus Atmodirono dengan penuh sukacita merayakan Pesta Nama Paroki tahun ini.</p>",
    coverImage: null,
    category: { id: 1, name: "Kegiatan Paroki", slug: "kegiatan-paroki", color: "#C9A84C" },
    author: { name: "Admin Paroki" },
    status: "published",
    isFeatured: true,
    publishedAt: new Date("2024-12-29"),
  },
  {
    id: 2,
    title: "Retret Kaum Muda Paroki — Menemukan Tuhan dalam Keheningan",
    slug: "retret-kaum-muda-paroki",
    excerpt: "Kaum muda Paroki Keluarga Kudus mengikuti retret selama 3 hari untuk memperdalam iman dan menemukan panggilan hidup masing-masing.",
    content: "<p>Sebanyak 80 kaum muda mengikuti retret yang dipandu oleh Rm. Andreas Wahyu, Pr.</p>",
    coverImage: null,
    category: { id: 2, name: "Kaum Muda", slug: "kaum-muda", color: "#7C9C6E" },
    author: { name: "Admin Paroki" },
    status: "published",
    isFeatured: true,
    publishedAt: new Date("2024-12-15"),
  },
  {
    id: 3,
    title: "Bakti Sosial: Kunjungan ke Panti Asuhan Santa Maria",
    slug: "bakti-sosial-panti-asuhan-santa-maria",
    excerpt: "Umat paroki bersama Tim Sosial melakukan kunjungan kasih ke Panti Asuhan Santa Maria dengan membawa bantuan sembako dan perlengkapan belajar.",
    content: "<p>Kegiatan bakti sosial rutin triwulan dilaksanakan dengan penuh semangat.</p>",
    coverImage: null,
    category: { id: 3, name: "Sosial", slug: "sosial", color: "#6B9BC9" },
    author: { name: "Admin Paroki" },
    status: "published",
    isFeatured: false,
    publishedAt: new Date("2024-12-01"),
  },
  {
    id: 4,
    title: "Penerimaan Sakramen Krisma 2024 — 120 Remaja Dikuatkan",
    slug: "sakramen-krisma-2024",
    excerpt: "Uskup Agung Semarang memberikan Sakramen Krisma kepada 120 remaja paroki dalam Misa Krisma yang khidmat dan penuh makna.",
    content: "<p>Momen sakral penerimaan Sakramen Krisma berlangsung di Gereja Paroki.</p>",
    coverImage: null,
    category: { id: 1, name: "Kegiatan Paroki", slug: "kegiatan-paroki", color: "#C9A84C" },
    author: { name: "Admin Paroki" },
    status: "published",
    isFeatured: false,
    publishedAt: new Date("2024-11-20"),
  },
  {
    id: 5,
    title: "Pendalaman Iman APP 2024: Merawat Bumi Ciptaan Tuhan",
    slug: "pendalaman-iman-app-2024",
    excerpt: "Kegiatan APP (Aksi Puasa Pembangunan) tahun ini berfokus pada tema lingkungan hidup sebagai tanggung jawab iman kita.",
    content: "<p>Selama masa APP, umat diajak untuk merenungkan pentingnya menjaga lingkungan.</p>",
    coverImage: null,
    category: { id: 4, name: "Iman & Spiritualitas", slug: "iman-spiritualitas", color: "#9B6B9B" },
    author: { name: "Admin Paroki" },
    status: "published",
    isFeatured: false,
    publishedAt: new Date("2024-03-10"),
  },
  {
    id: 6,
    title: "Natal 2024: Pesan Damai dalam Keberagaman",
    slug: "natal-2024-pesan-damai",
    excerpt: "Perayaan Natal Paroki Keluarga Kudus 2024 berlangsung meriah dengan penampilan paduan suara, drama natal, dan berbagi kasih bersama kaum dhuafa.",
    content: "<p>Semangat Natal tercermin dalam kebersamaan umat yang merayakannya.</p>",
    coverImage: null,
    category: { id: 1, name: "Kegiatan Paroki", slug: "kegiatan-paroki", color: "#C9A84C" },
    author: { name: "Admin Paroki" },
    status: "published",
    isFeatured: true,
    publishedAt: new Date("2024-12-25"),
  },
];

export const mockAnnouncements = [
  {
    id: 1,
    title: "Perubahan Jadwal Misa Minggu Pertama Bulan Mei",
    content: "Misa Minggu pertama bulan Mei akan dimulai pukul 08.00 WIB (mundur 1 jam) karena ada kegiatan renovasi sarana.",
    priority: "high",
    isActive: true,
  },
  {
    id: 2,
    title: "Pendaftaran Baptis Bayi Bulan Juni 2025",
    content: "Pendaftaran baptis bayi untuk bulan Juni dibuka mulai 5 Mei 2025 di Sekretariat Paroki.",
    priority: "normal",
    isActive: true,
  },
  {
    id: 3,
    title: "Kolekte Khusus: Dana Pembangunan Gereja",
    content: "Akan ada kolekte khusus untuk dana pembangunan renovasi Gereja pada Minggu, 11 Mei 2025.",
    priority: "normal",
    isActive: true,
  },
];

export const mockWarta = [
  {
    id: 1,
    title: "Warta Paroki Edisi 29 Desember 2024",
    editionDate: "2024-12-29",
    fileUrl: "#",
    description: "Warta Paroki minggu ini berisi informasi perayaan Pesta Nama Paroki dan berbagai kegiatan awal tahun.",
  },
  {
    id: 2,
    title: "Warta Paroki Edisi 22 Desember 2024",
    editionDate: "2024-12-22",
    fileUrl: "#",
    description: "Warta Paroki menjelang Natal dengan informasi jadwal Misa Natal dan berbagai kegiatan Adven.",
  },
  {
    id: 3,
    title: "Warta Paroki Edisi 15 Desember 2024",
    editionDate: "2024-12-15",
    fileUrl: "#",
    description: "Laporan kegiatan retret kaum muda dan informasi penerimaan krisma.",
  },
];

export const mockStats = {
  jumlahJemaat: 2847,
  komunitasKomunitas: 12,
  tahunBerdiri: 1952,
  kegiatanPerTahun: 48,
};

export const mockLiturgiColors = {
  putih: "Putih – Sukacita, Kemurnian (Natal, Paskah, Pesta Orang Kudus)",
  merah: "Merah – Roh Kudus, Kemartiran (Pentakosta, Jumat Agung)",
  hijau: "Hijau – Harapan, Pertumbuhan (Masa Biasa)",
  ungu: "Ungu – Pertobatan, Penantian (Adven, Prapaskah)",
  merahJambu: "Merah Jambu – Sukacita di Tengah Penantian (Minggu Gaudete & Laetare)",
  hitam: "Hitam – Berkabung (Misa Arwah)",
};
